#!/bin/bash
set -e

case "$1" in
    remove|upgrade|deconfigure)
        # Stop service before removal
        if [ -d /run/systemd/system ]; then
            if systemctl is-active --quiet vantagenet-daemon; then
                systemctl stop vantagenet-daemon
            fi
        fi
        ;;
esac

exit 0
